version: '3'

services: 
    pg:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./server:/app
        ports:
            - "5000:5000"
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=pg
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        expose: 
            - "5000"
        depends_on: 
            - pg
            - redis
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on: 
            - pg
    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./ui:/app
        ports:
            - "4200:4200"
        expose:
            - "4200"
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
        depends_on: 
            - api
            - ui 