FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf
# COPY ./default.conf /etc/nginx/conf.d/default.conf
# COPY ./default.conf /etc/ngix/sites-available/default.conf
# COPY ./ui /usr/share/nginx/html